image: node:18

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -r dist public
  artifacts:
    paths:
      - public
  only:
    - main
