name = "spacesos"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
vars = { NODE_ENV = "production" }

[site]
bucket = "./dist"
entry-point = "./"

[[routes]]
pattern = "spacesos.pages.dev/*"
custom_domain = true
