name = "monopereo-frontend"
type = "webpack"
account_id = "" # To be filled in by the user
workers_dev = true
route = ""
zone_id = "" # To be filled in by the user

[site]
bucket = "./frontend/dist"
entry-point = "workers-site"
