version: "1"

services:
  - hostname: backend
    type: python@3.9
    buildFromGit: .
    build:
      - pip install -r backend/requirements.txt
    start: uvicorn backend.app.main:app --host 0.0.0.0 --port 8080
    enableSubdomainAccess: true
    ports:
      - port: 8080
        http: true

  - hostname: frontend
    type: nodejs@18
    buildFromGit: .
    build:
      - cd frontend && npm install && npm run build
    static:
      - root: ./frontend/dist
    enableSubdomainAccess: true
